language: node_js

os:
  - osx

node_js:
  - "node"

env:
  global:
    - ELM_VERSION=0.18.0
    - ELM_TEST_VERSION=^0.18.2

install:
  - npm install -g elm@$ELM_VERSION
  - npm install -g elm-test@$ELM_TEST_VERSION

script:
  - make all test
